POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im15QGVtYWlsLmNvbSIsImV4cCI6MTcwNDU2MDgzOSwidXNlcklkIjoxfQ.flkN2DczomMq2uC4SCKtmT2UcEV7rArxRxmZMN3UKwA

{
    "name" : "Test event",
    "description" : "A test event",
    "location": "A test location",
    "datetime" : "2025-01-01T15:30:00.000Z"
} 