DELETE http://localhost:8080/events/6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im15ZW1haWwyQGVtYWlsLmNvbSIsImV4cCI6MTcwNDU1ODA3OCwidXNlcklkIjoyfQ.4JmO3EZReteH-3np217tYjyx7k8zgV39mroMzBmzrY4