PUT http://localhost:8080/events/1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im15QGVtYWlsLmNvbSIsImV4cCI6MTcwNDU2MDgzOSwidXNlcklkIjoxfQ.flkN2DczomMq2uC4SCKtmT2UcEV7rArxRxmZMN3UKwA

{
    "name": "Updated test event",
    "description": "Updated test event description",
    "datetime": "2025-01-01T15:30:00Z",
    "location": "Updated test event location"
}